"use client";

import { AdminFeedback, useAdminAction } from "@/components/admin/admin-action";
import { useI18n } from "@/components/i18n/i18n-provider";
import { Button } from "@/components/ui/button";

type ListingReport = { id: string; listingId: string; listingTitle: string; listingKind: string; reporterUsername: string | null; sellerUsername: string | null; reason: string; details: string | null; status: string; createdAt: string };
type ChatReport = { reportType: "message" | "conversation"; id: string; roomId: string; messageBody?: string; senderUsername?: string | null; reporterUsername: string | null; reportedUsername?: string | null; reason: string; details: string | null; status: string; createdAt: string; context?: Array<{ id: string; body: string; createdAt: string; senderUsername: string | null }> };

export function AdminReports({ listingReports, chatReports }: { listingReports: ListingReport[]; chatReports: ChatReport[] }) {
  const { t } = useI18n();
  const { pending, error, message, run } = useAdminAction();
  return (
    <div className="space-y-8">
      <section><h1 className="font-heading text-3xl font-semibold tracking-tight">{t("admin.listingReports")}</h1><p className="mt-2 text-sm text-muted-foreground">Review marketplace and direct-message reports.</p></section>
      <AdminFeedback error={error} message={message} />
      <section className="space-y-3"><h2 className="font-heading text-xl font-semibold">{t("admin.listingReports")}</h2><div className="space-y-3">{listingReports.map((report) => <article key={report.id} className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{report.listingTitle}</p><p className="mt-1 text-sm text-muted-foreground">{report.reason} · {report.reporterUsername ?? "anonymous"} · {report.createdAt}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={pending} onClick={() => run("review_listing_report", { reportId: report.id, reportStatus: "dismissed", resolutionNote: "Dismissed by admin" })}>{t("admin.dismissReport")}</Button><Button size="sm" variant="destructive" disabled={pending} onClick={() => run("review_listing_report", { reportId: report.id, reportStatus: "reviewed", removeListing: true, resolutionNote: "Listing removed by admin" })}>{t("admin.removeListing")}</Button></div></div>{report.details ? <p className="mt-3 text-sm text-muted-foreground">{report.details}</p> : null}</article>)}{!listingReports.length ? <p className="rounded-xl border border-dashed border-border px-4 py-8 text-center text-muted-foreground">{t("admin.noListingReports")}</p> : null}</div></section>
      <section className="space-y-3"><h2 className="font-heading text-xl font-semibold">{t("admin.chatReports")}</h2><div className="space-y-3">{chatReports.map((report) => <article key={report.id} className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{report.reportType === "message" ? report.messageBody : `${report.reportedUsername ?? "user"} · conversation`}</p><p className="mt-1 text-sm text-muted-foreground">{report.reason} · {report.reporterUsername ?? "anonymous"} · {report.createdAt}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={pending} onClick={() => run(report.reportType === "message" ? "review_chat_message_report" : "review_chat_room_report", { reportId: report.id, reportStatus: "dismissed", resolutionNote: "Dismissed by admin" })}>{t("admin.dismissReport")}</Button><Button size="sm" variant="destructive" disabled={pending} onClick={() => run(report.reportType === "message" ? "review_chat_message_report" : "review_chat_room_report", { reportId: report.id, reportStatus: "reviewed", ...(report.reportType === "message" ? { removeMessage: true } : {}), resolutionNote: "Actioned by admin" })}>{t("admin.removeMessage")}</Button></div></div>{report.details ? <p className="mt-3 text-sm text-muted-foreground">{report.details}</p> : null}{report.context?.length ? <div className="mt-3 space-y-1 rounded-lg bg-muted/40 p-3 text-xs">{report.context.slice(-5).map((item) => <p key={item.id}><strong>{item.senderUsername ?? "user"}:</strong> {item.body}</p>)}</div> : null}</article>)}{!chatReports.length ? <p className="rounded-xl border border-dashed border-border px-4 py-8 text-center text-muted-foreground">{t("admin.noChatReports")}</p> : null}</div></section>
    </div>
  );
}
